apiVersion: apps/v1
kind: Deployment
metadata:
  name: uporabnikova-shramba-izdelkov-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uporabnikova-shramba-izdelkov
  template:
    metadata:
      labels:
        app: uporabnikova-shramba-izdelkov
    spec:
      containers:
        - image: rsoskupina50/uporabnikova-shramba-izdelkov:2022-12-04-14-24-07
          name: uporabnikova-shramba-izdelkov
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://mouse.db.elephantsql.com/mzcgdhno
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: mzcgdhno
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: HNLXcZhB65htYCWwE5NALiLLS420Nn3T
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: uporabnikova-shramba-izdelkov
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: uporabnikova-shramba-izdelkov
